function(declare_local_target LIBRARY_TYPE PROJECT_NAME SOURCE_DIR)
  set("${PROJECT_NAME}_SRC_DIR" "src/${SOURCE_DIR}")
  file(GLOB_RECURSE "${PROJECT_NAME}_SRC" "${${PROJECT_NAME}_SRC_DIR}/*.*")
  add_library(${PROJECT_NAME} ${LIBRARY_TYPE} "${${PROJECT_NAME}_SRC}")
  target_include_directories(${PROJECT_NAME} PRIVATE "${${PROJECT_NAME}_SRC_DIR}")
  source_group(TREE "../../${${PROJECT_NAME}_SRC_DIR}" FILES "${${PROJECT_NAME}_SRC}")
endfunction()

function(declare_vst3_target VST3_PROJECT_NAME PLUG_PROJECT_NAME)
  set(TARGET_NAME "${VST3_PROJECT_NAME}.${INFERNAL_VERSION}.vst3")
  declare_local_target(SHARED ${TARGET_NAME} ${PLUG_PROJECT_NAME})
  target_include_directories(${TARGET_NAME} SYSTEM PRIVATE lib/vst3)
  target_include_directories(${TARGET_NAME} PRIVATE "src/${PLUG_PROJECT_NAME}" src/infernal.base src/infernal.base.vst3)
  target_link_libraries(${TARGET_NAME} ${PLUG_PROJECT_NAME} infernal.base infernal.base.vst3 pluginterfaces sdk sdk_common)
endfunction()